// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2017-12-04 11:31:35.5482733 -0200 -02 m=+0.003004601
// using data from
// D:\dev\go-land/src/github.com/ddspog/doni/version
package project

const version = "0.4.0-dev.1"
