// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2017-12-04 10:52:56.4450479 -0200 -02 m=+0.004002601
// using data from
// D:\dev\go-land/src/github.com/ddspog/doni/version
package project

const version = "0.2.0"
