// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2017-12-03 21:43:10.1991673 -0200 -02 m=+0.003002801
// using data from
// D:\dev\go-land/src/github.com/ddspog/doni/version
package project

const version = "0.1.1"
